export const USER_SCHEMA_NAME = 'user'
export const SERVICE_SCHEMA_NAME = 'service'
export const PRODUCT_SCHEMA_NAME = 'product'
export const CUSTOMER_SCHEMA_NAME = 'customer'
export const APPOINTMENT_SCHEMA_NAME = 'appointment'